;;; keybindings.el -*- lexical-binding: t; -*-

(defun yaz/toggle-profiler ()
  "Toggle emacs profiler."
  (interactive)
  (if (profiler-running-p)
      (progn
        (profiler-stop)
        (profiler-report))
    (profiler-start 'cpu+mem)
    (message "profiler started")))

(defun yaz/toggle-writing-mode ()
  "Toggle distraction-free writing layout (olivetti / centered text)."
  (interactive)
  (if (bound-and-true-p olivetti-mode)
      (progn
        (olivetti-mode -1)
        (message "writing mode off"))
    (progn
      (olivetti-mode 1)
      (message "writing mode on"))))

(global-set-key (kbd "C->") 'mc/mark-next-like-this)
(global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
(global-set-key (kbd "C-*") 'mc/mark-all-like-this)
(global-set-key (kbd "C-s-c C-s-c") 'mc/edit-lines)
(global-set-key (kbd "C-c g") 'yaz/search-on-browser)
(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
(global-set-key (kbd "<C-right>") 'next-buffer)
(global-set-key (kbd "<C-left>") 'previous-buffer)
(global-set-key (kbd "M-k") 'yaz/join-line-above)
(global-set-key (kbd "M-j") 'yaz/join-line-below)
(global-set-key (kbd "M-p") 'yaz/duplicate-line)
(global-set-key (kbd "M-<up>") 'yaz/move-line-up)
(global-set-key (kbd "M-<down>") 'yaz/move-line-down)
(global-set-key (kbd "C-h C-f") 'find-function)
(global-set-key (kbd "C-h C-v") 'find-variable)
(global-set-key (kbd "C-h C-k") 'find-function-on-key)

(use-package general
  :ensure t
  :demand t
  :config
  (general-create-definer leader-keys
    :states '(normal insert visual emacs)
    :keymaps 'override
    :prefix "SPC"
    :global-prefix "M-SPC")

  (leader-keys
    "SPC" '(counsel-M-x                          :wk "M-x")
    "."   '(counsel-find-file                    :wk "find file (here)")
    ","   '(ivy-switch-buffer                    :wk "switch buffer")
    "/"   '(comment-line                         :wk "comment region")
    ";"   '(eval-expression                      :wk "eval")
    "<"   '(swiper                               :wk "search buffer")
    "-"   '(swiper                               :wk "search (repeat)") 
    ">"   '(occur                                :wk "occur")
    "="   '(counsel-rg                           :wk "search (ripgrep)")
    "c"   '(project-compile                      :wk "compile (root)")
    "c"   '(compile                              :wk "compile (here)")
    "!"   '(project-shell-command                :wk "shell (root)")
    "1"   '(shell-command                        :wk "shell (here)")
    "j"   '(evil-switch-to-windows-last-buffer   :wk "last buffer")
    "RET" '(bookmark-jump                        :wk "bookmark"))

  (leader-keys
    "a"   '(:ignore t :wk "apps")
    "a a" '(mark-whole-buffer         :wk "select all")
    "a c" '(calculator                :wk "calculator")
    "a e" '(eshell                    :wk "eshell (here)")
    "a E" '(project-eshell            :wk "eshell (root)")
    "a o" '(counsel-linux-app         :wk "linux apps")
    "a t" '(term                      :wk "terminal")
    "a T" '(yaz/open-terminal-here    :wk "terminal (external)")
    "a v" '(vterm                     :wk "vterm")
    "a w" '(eww                       :wk "eww browser")
    "a -" '(dired-jump                :wk "dired (here)"))

  (leader-keys
    "&"   '(:ignore t :wk "shell")
    "& !" '(project-shell-command                 :wk "cmd (root)")
    "& h" '(shell-command                         :wk "cmd (here)")
    "& a" '(async-shell-command                   :wk "cmd (async)")
    "& r" '(project-async-shell-command           :wk "cmd (root async)")
    "& t" '(yaz/open-terminal-here                :wk "external term")
    "& e" '(project-eshell                        :wk "eshell (root)")
    "& E" '(eshell                                :wk "eshell (here)")
    "& v" '(project-shell                         :wk "shell (root)")
    "& V" '(vterm                                 :wk "vterm (here)"))

  (leader-keys
	"r"   '(:ignore t :wk "registers")
	"r r" '(list-registers             :wk "list registers")
	"r R" '(jump-to-register           :wk "jump to")
	"r s" '(copy-to-register           :wk "save to")
	"r i" '(insert-register            :wk "insert from")
	"r p" '(point-to-register          :wk "save position")
	"r w" '(window-configuration-to-register :wk "save windows")
	"r f" '(frameset-to-register       :wk "save frame")
	"r SPC" '(point-to-register        :wk "save point")
	"r +" '(increment-register         :wk "increment")
	"r n" '(number-to-register         :wk "save number"))

  (leader-keys
    "b"   '(:ignore t :wk "buffers")
    "b b" '(ivy-switch-buffer         :wk "switch")
    "b B" '(ibuffer                   :wk "ibuffer")
    "b k" '(kill-current-buffer       :wk "kill")
    "b K" '(kill-some-buffers         :wk "kill multiple")
    "b l" '(evil-switch-to-windows-last-buffer :wk "last")
    "b n" '(next-buffer               :wk "next")
    "b p" '(previous-buffer           :wk "previous")
    "b r" '(revert-buffer             :wk "revert")
    "b R" '(rename-buffer             :wk "rename")
    "b s" '(basic-save-buffer         :wk "save")
    "b S" '(save-some-buffers         :wk "save all")
    "b m" '(bookmark-set              :wk "set bookmark")
    "b l" '(list-bookmarks            :wk "list bookmarks"))

  (leader-keys
    "d"   '(:ignore t :wk "dired/debug")
    "d d" '(dired                     :wk "dired")
    "d j" '(dired-jump                :wk "dired (here)")
    "d w" '(wdired-change-to-wdired-mode :wk "wdired mode")
    "d g" '(gdb                       :wk "gdb")
    "d b" '(gud-break                 :wk "set breakpoint")
    "d r" '(gud-remove                :wk "remove breakpoint")
    "d n" '(gud-next                  :wk "step over")
    "d s" '(gud-step                  :wk "step into")
    "d c" '(gud-cont                  :wk "continue"))

  (leader-keys
    "e"   '(:ignore t :wk "errors/eval")
    "e b" '(eval-buffer               :wk "eval buffer")
    "e d" '(eval-defun                :wk "eval defun")
    "e e" '(eval-last-sexp            :wk "eval sexp")
    "e r" '(eval-region               :wk "eval region")
    "e l" '(flymake-show-project-diagnostics :wk "list errors (project)")
    "e L" '(flymake-show-buffer-diagnostics  :wk "list errors (buffer)")
    "e n" '(flymake-goto-next-error          :wk "next error")
    "e p" '(flymake-goto-prev-error          :wk "prev error"))

  (leader-keys
    "f"   '(:ignore t :wk "files")
    "f f" '(find-file                 :wk "find file")
    "f F" '(find-file-at-point        :wk "find at point")
    "f r" '(recentf-open-files        :wk "recent")
    "f s" '(save-buffer               :wk "save")
    "f S" '(write-file                :wk "save as")
    "f R" '(yaz/rename-file-and-buffer :wk "rename")
    "f d" '(yaz/delete-file-and-buffer :wk "delete")
    "f y" '(yaz/copy-file-path        :wk "copy path")
    "f Y" '(yaz/copy-file-name        :wk "copy name")

    "f l" '(counsel-locate            :wk "locate")
    "f m" '(yaz/make-file-executable  :wk "make executable")
    "f o" '(yaz/open-file-externally  :wk "open external")
    "f v" '(yaz/reveal-in-file-manager :wk "reveal in fm")
    "f t" '(yaz/move-file-to-trash    :wk "move to trash")
    "f m" '(yaz/make-file-executable  :wk "make executable")
    "f o" '(yaz/open-file-externally  :wk "open external")
    "f v" '(yaz/reveal-in-file-manager :wk "reveal in fm")
    "f t" '(yaz/move-file-to-trash    :wk "move to trash")
    "f c"   '(:ignore t :wk "config")
    "f c e" '((lambda () (interactive) (dired "~/.config/emacs/")) :wk "emacs dir")
    "f c i" '((lambda () (interactive) (find-file "~/.config/emacs/init.el")) :wk "init.el")
    "f c k" '((lambda () (interactive) (find-file "~/.config/emacs/configs/keybindings.el")) :wk "keybindings")
    "f c z" '((lambda () (interactive) (find-file "~/.zshrc")) :wk ".zshrc")
    "f c b" '((lambda () (interactive) (find-file "~/.bashrc")) :wk ".bashrc")
    "f c g" '((lambda () (interactive) (find-file "~/.gitconfig")) :wk ".gitconfig"))


  (leader-keys
    "h"     '(:ignore t :wk "help")
    "h a"   '(apropos                  :wk "apropos")
    "h b"   '(describe-bindings        :wk "bindings")
    "h c"   '(describe-char            :wk "char at point")
    "h f"   '(describe-function        :wk "function")
    "h F"   '(describe-face            :wk "face")
    "h i"   '(info                     :wk "info")
    "h k"   '(describe-key             :wk "key")
    "h l"   '(view-lossage             :wk "lossage")
    "h m"   '(describe-mode            :wk "mode")
    "h p"   '(describe-package         :wk "package")
    "h s"   '(describe-symbol          :wk "symbol")
    "h t"   '(load-theme               :wk "theme")
    "h v"   '(describe-variable        :wk "variable")
    "h r"   '(:ignore t :wk "reload")
    "h r r" '((lambda () (interactive) (load-file "~/.config/emacs/init.el")) :wk "reload config")
    "h r p" '(package-refresh-contents :wk "refresh packages"))

  (leader-keys
    "i"   '(:ignore t :wk "insert")
    "i c" '(insert-char               :wk "unicode char")
    "i d" '((lambda () (interactive) (insert (format-time-string "%Y-%M-%d"))) :wk "date")
    "i D" '((lambda () (interactive) (insert (format-time-string "%Y-%M-%d %H:%m:%S"))) :wk "datetime")
    "i f" '((lambda () (interactive) (insert (buffer-file-name))) :wk "file path")
    "i n" '((lambda () (interactive) (insert (buffer-name))) :wk "file name")
    "i s" '(yas-insert-snippet        :wk "snippet")
    "i u" '(counsel-unicode-char      :wk "unicode"))

  (leader-keys
    "l"   '(:ignore t :wk "eglot")
    "l l" '(eglot                     :wk "start")
    "l q" '(eglot-shutdown            :wk "shutdown")
    "l Q" '(eglot-shutdown-all        :wk "shutdown all")
    "l r" '(eglot-reconnect           :wk "reconnect")
    "l b" '(eglot-events-buffer       :wk "events buffer")
    "l a" '(eglot-code-actions        :wk "code action")
    "l f" '(eglot-format-buffer       :wk "format")
    "l F" '(eglot-format              :wk "format region")
    "l n" '(eglot-rename              :wk "rename")
    "l o" '(eglot-code-action-organize-imports :wk "organize imports")
    "l h" '(eldoc                     :wk "eldoc")
    "l d" '(xref-find-definitions   :wk "definition")
    "l D" '(eglot-find-declaration  :wk "declaration")
    "l i" '(eglot-find-implementation :wk "implementation")
    "l r" '(xref-find-references    :wk "references")
    "l t" '(eglot-find-typeDefinition :wk "type def")
    "l e " '(flymake-show-buffer-diagnostics :wk "list errors"))

  (leader-keys
    "p"   '(:ignore t :wk "project")
    "p p" '(project-switch-project           :wk "switch")
    "p f" '(project-find-file                :wk "find file")
    "p d" '(project-dired                    :wk "dired root")
    "p b" '(project-switch-to-buffer         :wk "buffer")
    "p k" '(project-kill-buffers             :wk "kill buffers")
    "p s"   '(:ignore t :wk "search")
    "p s s" '(project-find-regexp            :wk "grep")
    "p s r" '(project-query-replace-regexp   :wk "replace (regex)")
    "p c" '(project-compile                  :wk "compile")
    "p !" '(project-shell-command            :wk "shell command")
    "p &" '(project-async-shell-command      :wk "async shell cmd")
    "p e" '(project-eshell                   :wk "eshell")
    "p v" '(project-shell                    :wk "shell"))

  (leader-keys
    "s"   '(:ignore t :wk "search")
    "s b" '(isearch-forward           :wk "buffer")
    "s B" '(swiper-all                :wk "all buffers")
    "s f" '(project-find-file         :wk "find files")
    "s g" '(yaz/search-on-browser     :wk "google")
    "s I" '(imenu                     :wk "imenu")
    "s i" '(imenu-list                :wk "imenu list")
    "s l" '(counsel-locate            :wk "locate")
    "s o" '(occur                     :wk "occur")
    "s p" '(project-find-regexp       :wk "project")
    "s r" '(query-replace             :wk "replace")
    "s R" '(query-replace-regexp      :wk "replace regex")
    "s t" '(isearch-forward           :wk "text")
    "s m" '(man                       :wk "man")
    "s w" '(woman                     :wk "woman")
    "s t" '(tldr                      :wk "tldr"))

  (leader-keys
    "t"   '(:ignore t :wk "toggle")
    "t c" '(display-fill-column-indicator-mode :wk "fill column")
    "t f" '(toggle-frame-fullscreen   :wk "fullscreen")
    "t h" '(hl-line-mode              :wk "highlight line")
    "t i" '(indent-guide-mode         :wk "indent guide")
    "t l" '(display-line-numbers-mode :wk "line numbers")
    "t l" '(toggle-truncate-lines     :wk "truncate lines")
    "t p" '(yaz/toggle-profiler       :wk "profiler")
    "t r" '(read-only-mode            :wk "read only")
    "t s" '(flyspell-mode             :wk "spell check")
    "t v" '(visual-line-mode          :wk "visual line")
    "t w" '(whitespace-mode           :wk "whitespace")
    "t m" '(yaz/toggle-mouse-inhibit  :wk "mouse")
    "t w" '(delete-trailing-whitespace :wk "del trailing ws")
    "t z" '(yaz/toggle-writing-mode    :wk "zen mode")
    "t c" '(yaz/toggle-code-completion :wk "code completion"))

  (leader-keys
    "w"   '(:ignore t :wk "windows")
    "w w" '(other-window              :wk "other")
    "w d" '(delete-window             :wk "delete")
    "w D" '(delete-other-windows      :wk "delete others")
    "w s" '(split-window-below        :wk "split below")
    "w v" '(split-window-right        :wk "split right")
    "w h" '(windmove-left             :wk "move left")
    "w j" '(windmove-down             :wk "move down")
    "w k" '(windmove-up               :wk "move up")
    "w l" '(windmove-right            :wk "move right")
    "w h" '(evil-window-move-far-left :wk "move win left")
    "w j" '(evil-window-move-very-bottom :wk "move win down")
    "w k" '(evil-window-move-very-top :wk "move win up")
    "w l" '(evil-window-move-far-right :wk "move win right")
    "w =" '(balance-windows           :wk "balance")
    "w +" '(enlarge-window            :wk "enlarge v")
    "w -" '(shrink-window             :wk "shrink v")
    "w >" '(enlarge-window-horizontally :wk "enlarge h")
    "w <" '(shrink-window-horizontally :wk "shrink h")
    "w m" '(delete-other-windows      :wk "maximize")
    "w u" '(winner-undo               :wk "undo")
    "w r" '(winner-redo               :wk "redo"))

  (leader-keys
    "x"   '(:ignore t :wk "system")
    "x D" '(yaz/disk-usage            :wk "disk usage")
    "x m" '(yaz/memory-usage          :wk "memory")
    "x i" '(yaz/ip-info               :wk "ip info")
    "x I" '(yaz/ip-public             :wk "public ip")
    "x o" '(yaz/ports                 :wk "ports")
    "x h" '(yaz/htop                  :wk "htop")
    "x b" '(yaz/btop                  :wk "btop")
    "x c" '(yaz/cpu-info              :wk "cpu info")
    "x s" '(yaz/system-info           :wk "system info")
    "x n" '(yaz/network-connections   :wk "network")
    "x P" '(yaz/ping-host             :wk "ping")
    "x u" '(yaz/disk-usage-here       :wk "disk (here)")
    "x j" '(yaz/journal-logs          :wk "journal logs")
    "x U" '(yaz/update-system         :wk "system update")

    "x e"   '(:ignore t :wk "processes (emacs)")
    "x e l" '(list-processes          :wk "list emacs procs")
    "x e k" '(kill-process            :wk "kill process")
    "x e K" '(kill-process-force      :wk "kill -9 process")
    "x e s" '(signal-process          :wk "signal process")

    "x p"   '(:ignore t :wk "processes (external)")
    "x p l" '(yaz/list-processes      :wk "list")
    "x p k" '(yaz/kill-process        :wk "kill")
    "x p K" '(yaz/kill-process-force  :wk "kill -9")
    "x p s" '(yaz/signal-process      :wk "signal")

    "x d"   '(:ignore t :wk "docker (containers)")
    "x d l" '(yaz/list-containers     :wk "list")
    "x d s" '(yaz/docker-stop         :wk "stop")
    "x d k" '(yaz/docker-kill         :wk "kill")
    "x d r" '(yaz/docker-restart      :wk "restart")
    "x d L" '(yaz/docker-logs         :wk "logs"))

  (leader-keys
    "z"   '(:ignore t :wk "fold/zoom")
    "z a" '(hs-toggle-hiding          :wk "toggle fold")
    "z c" '(hs-hide-block             :wk "fold")
    "z o" '(hs-show-block             :wk "unfold")
    "z m" '(hs-hide-all               :wk "fold all")
    "z r" '(hs-show-all               :wk "unfold all")
    "z +" '(text-scale-increase       :wk "zoom in")
    "z -" '(text-scale-decrease       :wk "zoom out")
    "z 0" '(text-scale-adjust         :wk "reset zoom"))

  (leader-keys
    "m"   '(:ignore t :wk "emacs")
    "m p"   '(:ignore t :wk "packages")
    "m p l" '(package-list-packages   :wk "list packages")
    "m p r" '(package-refresh-contents :wk "refresh")
    "m p i" '(package-install         :wk "install")
    "m p d" '(package-delete          :wk "delete")
    "m p u" '(package-upgrade-all     :wk "upgrade all")
    "m p a" '(package-autoremove      :wk "autoremove")
    "m i"   '(:ignore t :wk "info")
    "m i e" '(emacs-version           :wk "emacs version")
    "m i i" '(emacs-init-time         :wk "init time")
    "m i m" '(memory-report           :wk "memory report")
    "m i p" '(list-processes          :wk "processes")
    "m i t" '(list-timers             :wk "timers")
    "m i f" '(list-faces-display      :wk "faces")
    "m i c" '(list-colors-display     :wk "colors")
    "m i k" '(view-lossage            :wk "key lossage")
    "m c"   '(:ignore t :wk "customize")
    "m c c" '(customize               :wk "customize")
    "m c g" '(customize-group         :wk "group")
    "m c v" '(customize-variable      :wk "variable")
    "m c f" '(customize-face          :wk "face")
    "m c t" '(customize-themes        :wk "themes")
    "m m"   '(:ignore t :wk "modes")
    "m m a" '(auto-fill-mode          :wk "auto fill")
    "m m c" '(column-number-mode      :wk "column number")
    "m m e" '(electric-pair-mode      :wk "electric pair")
    "m m f" '(flymake-mode            :wk "flymake")
    "m m h" '(hl-line-mode            :wk "highlight line")
    "m m l" '(linum-mode              :wk "line numbers")
    "m m o" '(outline-minor-mode      :wk "outline")
    "m m p" '(show-paren-mode         :wk "show parens")
    "m m s" '(subword-mode            :wk "subword")
    "m m w" '(whitespace-mode         :wk "whitespace")
    "m m v" '(visual-line-mode        :wk "visual line")
    "m d"   '(:ignore t :wk "debug")
    "m d d" '(toggle-debug-on-error   :wk "debug on error")
    "m d q" '(toggle-debug-on-quit    :wk "debug on quit")
    "m d e" '(edebug-defun            :wk "edebug defun")
    "m d t" '(trace-function          :wk "trace function")
    "m d u" '(untrace-function        :wk "untrace function")
    "m d u" '(untrace-all             :wk "untrace all"))

  (leader-keys
    "n"   '(:ignore t :wk "narrow/notes")
    "n n" '(narrow-to-region          :wk "narrow region")
    "n d" '(narrow-to-defun           :wk "narrow defun")
    "n p" '(narrow-to-page            :wk "narrow page")
    "n w" '(widen                     :wk "widen")
    "n a" '(org-agenda                :wk "org agenda")
    "n +" '(yaz/increment-number-at-point :wk "increment")
    "n -" '(yaz/decrement-number-at-point :wk "decrement"))

  (leader-keys
    "o"   '(:ignore t :wk "org")
    "o a" '(org-agenda                :wk "agenda")
    "o c" '(org-capture               :wk "capture")
    "o l" '(org-store-link            :wk "store link")

    "o f"   '(:ignore t :wk "files")
    "o f s" '(yaz/find-school-file    :wk "find school file")
    "o f S" '(yaz/new-school-file     :wk "new school file")
    "o f p" '(yaz/find-project-file   :wk "find project file")
    "o f P" '(yaz/new-project-file    :wk "new project file")
    "o f l" '(yaz/find-learning-file  :wk "find learning file")
    "o f L" '(yaz/new-learning-file   :wk "new learning file")
    "o f f" '(yaz/open-org-file       :wk "find any org file")

    "o n"   '(:ignore t :wk "roam")
    "o n f" '(org-roam-node-find      :wk "find node")
    "o n i" '(org-roam-node-insert    :wk "insert node")
    "o n c" '(org-roam-capture        :wk "capture")
    "o n l" '(org-roam-buffer-toggle  :wk "toggle buffer")
    "o n t" '(org-roam-dailies-goto-today :wk "today's daily")

    "o r"   '(:ignore t :wk "research")
    "o r r" '(yaz/create-paper-review-from-bib :wk "review from bib")
    "o r f" '(yaz/create-paper-review-from-pdf :wk "review from pdf")
    "o r c" '(citar-insert-citation   :wk "insert citation")
    "o r o" '(citar-open              :wk "open paper")
    "o r n" '(citar-open-notes        :wk "open notes")
    "o r l" '(citar-open-link         :wk "open link"))

)

(add-hook 'prog-mode-hook #'hs-minor-mode)

(winner-mode 1)

(provide 'keybindings)
;;; keybindings.el ends here
